[env]
_.file = '.env'

[tools]
node = "24"
pnpm = "10"

[tasks.dev]
description = "Start the SST development server"
run = "pnpm sst:dev"

[tasks.deploy]
description = "Deploy the SST production server"
run = "pnpm prod-deploy"

[tasks.remove]
description = "Remove the SST production server"
run = "pnpm prod-remove"

[tasks."pre-commit"]
description = "Execute before commit"
run = """
pnpm check
"""

[hooks]
postinstall = """
pnpm install
mise generate git-pre-commit --write --task=pre-commit
"""
