name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: jdx/mise-action@v2
      
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Enable mise experimental features
        run: mise settings experimental=true

      - name: Install dependencies
        run: mise install
        
      - name: Deploy
        run: mise run deploy
